### ISSUE TITLE
Android Client

### ISSUE THREAD

**Issue by erikjhordan-rey** [pacevedo/Eurocopa2016#1]
Hola, Estoy buscando alguna API para la Eurocopa 2016 me gustaría hacer una app en android y hacer el código open source también.  Estas haciendo scraping del sitio oficial? Expondrás el API?

**Comment by pacevedo** [comment]
Hola, 

Estoy intentando hacer una aplicación con el stack MEAN (MongoDB, Express, AngularJS y NodeJS) que valdrá para hacer un juego de pronósticos con mis amigos. No voy a hacer scraping, los datos los introduzco yo manualmente, ya que no son muchos. El código va a estar disponible, pero no sé si te valdrá para algo

**Comment by erikjhordan-rey** [comment]
vale, gracias!
